#! /bin/bash

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=600 --HighMRcut=10000 --LowRSQcut=0.025 --HighRSQcut=100 --outputFile=highpt_bin0_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=150 --HighMRcut=600 --LowRSQcut=0.13 --HighRSQcut=100 --outputFile=highpt_bin1_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=1250 --HighMRcut=10000 --LowRSQcut=0.0 --HighRSQcut=0.025 --outputFile=highpt_bin2_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=150 --HighMRcut=450 --LowRSQcut=0.0 --HighRSQcut=0.13 --outputFile=highpt_bin3_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=450 --HighMRcut=600 --LowRSQcut=0.0 --HighRSQcut=0.035 --outputFile=highpt_bin4_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=450 --HighMRcut=600 --LowRSQcut=0.035 --HighRSQcut=0.13 --outputFile=highpt_bin5_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=600 --HighMRcut=1250 --LowRSQcut=0.0 --HighRSQcut=0.015 --outputFile=highpt_bin6_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highpt --detector=ebeb --LowMRcut=600 --HighMRcut=1250 --LowRSQcut=0.015 --HighRSQcut=0.025 --outputFile=highpt_bin7_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=hzbb --detector=ebeb --LowMRcut=150 --HighMRcut=10000 --LowRSQcut=0.0 --HighRSQcut=100 --outputFile=highpt_bin8_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highres --detector=ebeb --LowMRcut=150 --HighMRcut=250 --LowRSQcut=0.0 --HighRSQcut=0.175 --outputFile=highpt_bin9_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highres --detector=ebeb --LowMRcut=150 --HighMRcut=250 --LowRSQcut=0.175 --HighRSQcut=100 --outputFile=highpt_bin10_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highres --detector=ebeb --LowMRcut=250 --HighMRcut=10000 --LowRSQcut=0.05 --HighRSQcut=100 --outputFile=highpt_bin11_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highres --detector=ebeb --LowMRcut=250 --HighMRcut=600 --LowRSQcut=0.0 --HighRSQcut=0.05 --outputFile=highpt_bin12_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=highres --detector=ebeb --LowMRcut=600 --HighMRcut=10000 --LowRSQcut=0.0 --HighRSQcut=0.05 --outputFile=highpt_bin13_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=500 --HighMRcut=10000 --LowRSQcut=0.01 --HighRSQcut=100 --outputFile=highpt_bin14_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=150 --HighMRcut=500 --LowRSQcut=0.15 --HighRSQcut=100 --outputFile=highpt_bin15_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=150 --HighMRcut=400 --LowRSQcut=0.0 --HighRSQcut=0.15 --outputFile=highpt_bin16_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=400 --HighMRcut=500 --LowRSQcut=0.0 --HighRSQcut=0.015 --outputFile=highpt_bin17_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=400 --HighMRcut=500 --LowRSQcut=0.015 --HighRSQcut=0.15 --outputFile=highpt_bin18_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=500 --HighMRcut=800 --LowRSQcut=0.0 --HighRSQcut=0.01 --outputFile=highpt_bin19_sbFit.root

./MakeFitRun2 --treeName=HggRazor --inputFile=/Users/cmorgoth/Work/data/HggRazor/2015_2016/V3p4_PhotonCorrJuly8_RegularSelectionSequence/HggRazor_DoubleEG_Run2_MRSkim_2p3+8p3ifb_DCS.root --fitMode=sb --runPeriod=run2 --inputFileSignal=/Users/cmorgoth/Work/data/HggRazor/2016/Signal/HggRazor_SMS-T2bH_mSbottom-300_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_1pb_weighted.root --inputFileSMH=/Users/cmorgoth/Work/data/HggRazor/2016/SMH/HggRazor_ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_TOTAL_1pb_weighted.root --dataMode=data+signal --category=lowres --detector=ebeb --LowMRcut=800 --HighMRcut=10000 --LowRSQcut=0.0 --HighRSQcut=0.01 --outputFile=highpt_bin20_sbFit.root
